package items

import (
	"time"

	"github.com/janisto/huma-playground/internal/platform/timeutil"
)

// Item represents a sample resource for pagination demonstration.
type Item struct {
	ID          string        `json:"id"          doc:"Unique identifier"                example:"item-001"                 minLength:"1" maxLength:"128"`
	Name        string        `json:"name"        doc:"Display name"                     example:"Alpha Widget"             minLength:"1" maxLength:"100"`
	Category    string        `json:"category"    doc:"Item category"                    example:"electronics"                                            enum:"electronics,tools,accessories,robotics,power,components"`
	Price       Money         `json:"price"       doc:"Exact price in USD"`
	InStock     bool          `json:"inStock"     doc:"Availability status"              example:"true"`
	CreatedAt   timeutil.Time `json:"createdAt"   doc:"Creation timestamp"               example:"2024-01-15T10:30:00.000Z"                                                                                              format:"date-time"`
	Description string        `json:"description" doc:"Detailed description of the item"                                    minLength:"1" maxLength:"500"`
}

// Money is an exact integer-minor-unit USD price.
type Money struct {
	AmountMinor int64  `json:"amountMinor" minimum:"0" maximum:"9007199254740991" example:"2999"`
	Currency    string `json:"currency"                                           example:"USD"  enum:"USD"`
}

// mockItems provides sample data for pagination demonstration.
var mockItems = []Item{
	{
		ID:          "item-001",
		Name:        "Alpha Widget",
		Category:    "electronics",
		Price:       Money{AmountMinor: 2999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 15, 10, 30, 0, 0, time.UTC)),
		Description: "A versatile electronic widget for everyday use",
	},
	{
		ID:          "item-002",
		Name:        "Beta Gadget",
		Category:    "electronics",
		Price:       Money{AmountMinor: 4999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 16, 11, 0, 0, 0, time.UTC)),
		Description: "Advanced gadget with smart features",
	},
	{
		ID:          "item-003",
		Name:        "Gamma Tool",
		Category:    "tools",
		Price:       Money{AmountMinor: 1550, Currency: "USD"},
		InStock:     false,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 17, 9, 15, 0, 0, time.UTC)),
		Description: "Precision tool for professional work",
	},
	{
		ID:          "item-004",
		Name:        "Delta Component",
		Category:    "electronics",
		Price:       Money{AmountMinor: 899, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 18, 14, 45, 0, 0, time.UTC)),
		Description: "Essential component for electronics projects",
	},
	{
		ID:          "item-005",
		Name:        "Epsilon Sensor",
		Category:    "electronics",
		Price:       Money{AmountMinor: 3499, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 19, 8, 0, 0, 0, time.UTC)),
		Description: "High-precision environmental sensor",
	},
	{
		ID:          "item-006",
		Name:        "Zeta Cable",
		Category:    "accessories",
		Price:       Money{AmountMinor: 1299, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 20, 16, 30, 0, 0, time.UTC)),
		Description: "Premium quality data cable",
	},
	{
		ID:          "item-007",
		Name:        "Eta Adapter",
		Category:    "accessories",
		Price:       Money{AmountMinor: 999, Currency: "USD"},
		InStock:     false,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 21, 10, 0, 0, 0, time.UTC)),
		Description: "Universal power adapter",
	},
	{
		ID:          "item-008",
		Name:        "Theta Board",
		Category:    "electronics",
		Price:       Money{AmountMinor: 8999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 22, 11, 30, 0, 0, time.UTC)),
		Description: "Development board for prototyping",
	},
	{
		ID:          "item-009",
		Name:        "Iota Switch",
		Category:    "electronics",
		Price:       Money{AmountMinor: 599, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 23, 9, 45, 0, 0, time.UTC)),
		Description: "Tactile push button switch",
	},
	{
		ID:          "item-010",
		Name:        "Kappa Display",
		Category:    "electronics",
		Price:       Money{AmountMinor: 4599, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 24, 13, 0, 0, 0, time.UTC)),
		Description: "OLED display module",
	},
	{
		ID:          "item-011",
		Name:        "Lambda Motor",
		Category:    "robotics",
		Price:       Money{AmountMinor: 2499, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 25, 8, 30, 0, 0, time.UTC)),
		Description: "DC motor for robotics projects",
	},
	{
		ID:          "item-012",
		Name:        "Mu Servo",
		Category:    "robotics",
		Price:       Money{AmountMinor: 1899, Currency: "USD"},
		InStock:     false,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 26, 15, 0, 0, 0, time.UTC)),
		Description: "High-torque servo motor",
	},
	{
		ID:          "item-013",
		Name:        "Nu Battery",
		Category:    "power",
		Price:       Money{AmountMinor: 1499, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 27, 10, 15, 0, 0, time.UTC)),
		Description: "Rechargeable lithium battery pack",
	},
	{
		ID:          "item-014",
		Name:        "Xi Charger",
		Category:    "power",
		Price:       Money{AmountMinor: 2299, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 28, 11, 45, 0, 0, time.UTC)),
		Description: "Smart battery charger",
	},
	{
		ID:          "item-015",
		Name:        "Omicron Relay",
		Category:    "electronics",
		Price:       Money{AmountMinor: 799, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 29, 9, 0, 0, 0, time.UTC)),
		Description: "5V relay module",
	},
	{
		ID:          "item-016",
		Name:        "Pi Controller",
		Category:    "electronics",
		Price:       Money{AmountMinor: 5599, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 1, 30, 14, 30, 0, 0, time.UTC)),
		Description: "Microcontroller board",
	},
	{
		ID:          "item-017",
		Name:        "Rho Resistor Kit",
		Category:    "components",
		Price:       Money{AmountMinor: 1199, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 1, 8, 0, 0, 0, time.UTC)),
		Description: "Assorted resistor pack",
	},
	{
		ID:          "item-018",
		Name:        "Sigma Capacitor Set",
		Category:    "components",
		Price:       Money{AmountMinor: 1399, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 2, 10, 30, 0, 0, time.UTC)),
		Description: "Electrolytic capacitor assortment",
	},
	{
		ID:          "item-019",
		Name:        "Tau LED Pack",
		Category:    "components",
		Price:       Money{AmountMinor: 699, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 3, 11, 0, 0, 0, time.UTC)),
		Description: "Multi-color LED assortment",
	},
	{
		ID:          "item-020",
		Name:        "Upsilon Wire Set",
		Category:    "accessories",
		Price:       Money{AmountMinor: 899, Currency: "USD"},
		InStock:     false,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 4, 9, 15, 0, 0, time.UTC)),
		Description: "Jumper wire kit",
	},
	{
		ID:          "item-021",
		Name:        "Phi Breadboard",
		Category:    "tools",
		Price:       Money{AmountMinor: 499, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 5, 13, 45, 0, 0, time.UTC)),
		Description: "Solderless breadboard",
	},
	{
		ID:          "item-022",
		Name:        "Chi Soldering Iron",
		Category:    "tools",
		Price:       Money{AmountMinor: 3599, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 6, 10, 0, 0, 0, time.UTC)),
		Description: "Temperature-controlled soldering station",
	},
	{
		ID:          "item-023",
		Name:        "Psi Multimeter",
		Category:    "tools",
		Price:       Money{AmountMinor: 4299, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 7, 11, 30, 0, 0, time.UTC)),
		Description: "Digital multimeter with auto-ranging",
	},
	{
		ID:          "item-024",
		Name:        "Omega Oscilloscope",
		Category:    "tools",
		Price:       Money{AmountMinor: 29999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 8, 14, 0, 0, 0, time.UTC)),
		Description: "Portable digital oscilloscope",
	},
	{
		ID:          "item-025",
		Name:        "Alpha Pro Widget",
		Category:    "electronics",
		Price:       Money{AmountMinor: 5999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 9, 8, 30, 0, 0, time.UTC)),
		Description: "Professional-grade widget with extended features",
	},
	{
		ID:          "item-026",
		Name:        "Beta Max Gadget",
		Category:    "electronics",
		Price:       Money{AmountMinor: 7999, Currency: "USD"},
		InStock:     false,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 10, 9, 0, 0, 0, time.UTC)),
		Description: "Maximum performance gadget",
	},
	{
		ID:          "item-027",
		Name:        "Gamma Plus Tool",
		Category:    "tools",
		Price:       Money{AmountMinor: 2599, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 11, 10, 15, 0, 0, time.UTC)),
		Description: "Enhanced precision tool",
	},
	{
		ID:          "item-028",
		Name:        "Delta Ultra Component",
		Category:    "electronics",
		Price:       Money{AmountMinor: 1699, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 12, 11, 45, 0, 0, time.UTC)),
		Description: "Ultra-reliable component",
	},
	{
		ID:          "item-029",
		Name:        "Epsilon HD Sensor",
		Category:    "electronics",
		Price:       Money{AmountMinor: 5499, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 13, 13, 0, 0, 0, time.UTC)),
		Description: "High-definition sensor array",
	},
	{
		ID:          "item-030",
		Name:        "Zeta Premium Cable",
		Category:    "accessories",
		Price:       Money{AmountMinor: 1999, Currency: "USD"},
		InStock:     true,
		CreatedAt:   timeutil.NewTime(time.Date(2024, 2, 14, 15, 30, 0, 0, time.UTC)),
		Description: "Gold-plated premium cable",
	},
}
