name: Run unit tests and upload coverage report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Validate Go toolchain
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests with coverage
        run: go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

      - name: Generate coverage artifacts
        run: |
          go tool cover -func=coverage.out > coverage-summary.txt
          go tool cover -html=coverage.out -o coverage.html

      - name: Publish coverage summary
        run: |
          total=$(grep '^total:' coverage-summary.txt | awk '{print $3}')
          {
            echo "### Test Coverage"
            echo
            echo "Total coverage: ${total}"
            echo
            echo '```'
            cat coverage-summary.txt
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html
            coverage-summary.txt
